### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by juddey** [irvin373/fullscreenVideoAndroid#9]
Just wanted to say thanks for posting this repo, now have full screen player going on android in my react-native app. :raised_hands:

Feel free to close.

**Comment by irvin373** [comment]
sure, you can read maybe this "https://medium.com/@irvin373/react-native-fullscreen-player-ac68925c53cc", all code needed is on there, I think is a bad idea 😅 fork this old example.

**Comment by juddey** [comment]
Ha, I used that code anyways. So no worries! Thank you.
